WebShop/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.staticfiles.urls import staticfiles_urlpatterns

admin.autodiscover()

urlpatterns = [
    path('admin/', admin.site.urls),
    path('admin_tools/', include('admin_tools.urls')),
    path(r'nested_admin/', include('nested_admin.urls')),

    path('', include('shop.urls')),


]

urlpatterns += staticfiles_urlpatterns()

# urlpatterns += static(settings.STATIC_URL, document_root=settings.)

# urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
#

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

shop/urls.py
from django.urls import path
from django.conf.urls import url

from . import views

app_name = 'shop'

urlpatterns = [
    path('', views.home_page, name='index'),
    path('cart/', views.cart_page, name='cart'),
    path('about/', views.about_page, name='about'),
    path('shop/category/<int:pk>/', views.product_page, name='product'),
    path('shop/product/<int:pk>', views.product_detail_page, name='product_detail'),
    path('shop/product/addcard', views.addCart, name='add_cart'),
    path('shop/product/delete', views.delete_item, name='delete_item'),
    path('shop/product/modify', views.changeAmount, name='modify'),
    path('shop/product/add_comment', views.add_comment, name='add_comment'),
    path('shop/product/make_order', views.make_order, name='make_order'),
    path('shop/product/order_confirmation', views.confirmation, name='confirmation'),
    path('shop/callback', views.callback, name='callback'),
    path('privacy/', views.privacy, name='privacy'),
    path('oferta/', views.oferta, name='oferta'),

]

shop/models.py
from django.db import models
import datetime

STATUS = [
    ('Не проверен', 'Не проверен'),
    ('Проверен', 'Проверен'),
    ('Оплачен', 'Оплачен'),
    ('Отклонён', 'Отклонён')
]


class Question(models.Model):
    question = models.CharField(max_length=255, help_text="(максимальное число символов: 255)",
                                verbose_name="Вопрос ")
    answer = models.TextField(verbose_name="Ответ ")

    def __str__(self):
        return f'Вопрос: {self.question}'

    class Meta:
        verbose_name = "Частый вопрос"
        verbose_name_plural = "Частые вопросы"


class Calling(models.Model):
    full_name = models.CharField(max_length=255, verbose_name="Вопрос клиента")
    phone = models.CharField(max_length=50, verbose_name="Номер телефона клиента")

    def __str__(self):
        return f'имя: {self.full_name}  телефон: {self.phone}'

    class Meta:
        verbose_name = "Заявка на обратную связь"
        verbose_name_plural = "Заявки на обратную связь"


class Tag(models.Model):
    name = models.CharField(max_length=255, help_text="(максимальное число символов: 255)",
                            verbose_name="Название тэга ")
    desc = models.TextField(verbose_name="Описание тэга ", help_text="необязательно, только для вас",
                            default="Не указан")

    def __str__(self):
        return f'{self.name}'

    class Meta:
        verbose_name = "Тэг"
        verbose_name_plural = "Тэги"


class Category(models.Model):
    name = models.CharField(max_length=255, help_text="(максимальное число символов: 255)",
                            verbose_name="Название категории ")
    desc = models.TextField(verbose_name="Описание категории ", help_text="необязательно, только для вас",
                            default="Не указан")
    banner = models.ImageField(help_text="(соотношение 2.39:1 или любой широкоформатный)",
                               verbose_name="Главное фото на странице категории ", upload_to='media/category_banners')

    banner_alt = models.CharField(max_length=255, help_text="(необязательно, нужен только для сео)",
                                  verbose_name="Название фотографии для ALT",
                                  default="Главное фото категории")

    def __str__(self):
        return f'{self.name}'

    class Meta:
        verbose_name = "Категория"
        verbose_name_plural = "Категории"


class Subcategory(models.Model):
    category = models.ForeignKey(Category, on_delete=models.CASCADE, verbose_name="Выбор категории ")
    name = models.CharField(max_length=255, help_text="(максимальное число символов: 255)",
                            verbose_name="Название подкатегории ")

    def __str__(self):
        return f'{self.name}'

    class Meta:
        verbose_name = "Под категория"
        verbose_name_plural = "Под категории"


class Property(models.Model):
    name = models.CharField(max_length=255, help_text="(максимальное число символов: 255)",
                            verbose_name="Название фильтра ")

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = "Фильтр"
        verbose_name_plural = "Фильтры"


class Product(models.Model):
    name = models.CharField(max_length=255, help_text="(максимальное число символов: 255)",
                            verbose_name="Название товара ")
    subcategory = models.ForeignKey(Subcategory, on_delete=models.CASCADE,
                                    verbose_name="Выбор подкатегории ")
    tag = models.ForeignKey(Tag, on_delete=models.DO_NOTHING, null=True,
                            verbose_name="Выбор тэга ", blank=True)
    desc = models.TextField(verbose_name="Полное описание товара ")

    desc_short = models.CharField(max_length=255, help_text="(максимальное число символов: 255)",
                                  verbose_name="Короткое описание товара ")

    def __str__(self):
        return f'Название: {self.name} Подкатегория: {self.subcategory.name}'

    class Meta:
        verbose_name = "Товар"
        verbose_name_plural = "Товары"


class ProductComment(models.Model):
    prod = models.ForeignKey(Product, on_delete=models.CASCADE, verbose_name="Название товара ")
    text = models.TextField(verbose_name="Текст комментария ")
    rate = models.IntegerField(default=0, help_text="от 0 до 5",
                               verbose_name="Оценка ")
    user_name = models.CharField(max_length=255,
                                 verbose_name="ФИО комментатора")
    phone_number = models.CharField(max_length=255,
                                    verbose_name="Телефон комментатора ")
    pub_date = models.DateField(default=datetime.date.today)

    def __str__(self):
        return f'ФИО: {self.prod.name} Оценка: {self.rate} Телефон: {self.phone_number} Дата: {self.pub_date}'

    class Meta:
        verbose_name = "Отзыв"
        verbose_name_plural = "Отзывы"


class ProductPhoto(models.Model):
    prod = models.ForeignKey(Product, on_delete=models.CASCADE,
                             verbose_name="Выбор товара ")
    img = models.ImageField(upload_to='media/product_photos',
                            help_text="(соотношение 1:1 или вертикальный прямоугольник, ВАЖНО: первая картинка будет видна на карте товара, остальные только на странице товара)",
                            verbose_name="Фотография товара ")
    alt = models.CharField(max_length=255, help_text="(необязательно, нужен только для сео)",
                           verbose_name="Название фотографии для ALT",
                           default="Фото товара")

    def __str__(self):
        return f'Товар: {self.prod.name}  ALT: {self.alt}'

    class Meta:
        verbose_name = "Фото"
        verbose_name_plural = "Фотографии"


class ProductVideo(models.Model):
    prod = models.ForeignKey(Product, on_delete=models.CASCADE, verbose_name="Выбор товара ")
    video = models.FileField(upload_to='media/video', help_text="(видео для страницы товара)",
                             verbose_name="Видео о товаре ")
    alt = models.CharField(max_length=255, help_text="(необязательно, нужен только для сео)",
                           verbose_name="Название видео для ALT",
                           default="Видео о товаре")

    def __str__(self):
        return f'Товар: {self.prod.name}  ALT: {self.alt}'

    class Meta:
        verbose_name = "Видео"
        verbose_name_plural = "Видео"


class ProductChar(models.Model):
    prod = models.ForeignKey(Product, on_delete=models.CASCADE, verbose_name="Выбор товара ")
    price = models.IntegerField(verbose_name="Цена товара",
                                default=10000)
    sold = models.IntegerField(default=0, editable=False)
    amount = models.IntegerField(default=0, help_text="(необязательно, только для вас)",
                                 verbose_name="Количество товара")
    props = models.ManyToManyField(Property, through='ProdVal',
                                   verbose_name="Выбор фильтра(ов) ")

    def __str__(self):
        return f'Товар: {self.prod.name} Цена: {self.price} Продано: {self.sold} Осталось: {self.amount}'

    class Meta:
        verbose_name = "Опция товара"
        verbose_name_plural = "Опции товаров"


class ProdVal(models.Model):
    value = models.CharField(max_length=255, help_text="(максимальное число символов: 255)",
                             verbose_name="Значение ")
    prop = models.ForeignKey(Property, on_delete=models.CASCADE,
                             verbose_name="Выбор фильтра ")
    prod_char = models.ForeignKey(ProductChar, on_delete=models.CASCADE, verbose_name="Выбор товара ")

    def __str__(self):
        return f'{self.prop.name} - {self.value}'

    class Meta:
        verbose_name = "Значение"
        verbose_name_plural = "Значения"


class Cart(models.Model):
    session_key = models.CharField(max_length=128, blank=True, null=True, default=None, editable=False)


class CartProduct(models.Model):
    cart = models.ForeignKey(Cart, on_delete=models.CASCADE, blank=True, null=True, default=None)
    product = models.ForeignKey(ProductChar, on_delete=models.CASCADE, blank=True, null=True, default=None)
    amount = models.IntegerField(default=1, verbose_name="Заказано")

    class Meta:
        verbose_name = "Товар в корзине"
        verbose_name_plural = "Товары в корзине"

    def __str__(self):
        return f"{self.product.prod.name}"


class Article(models.Model):
    title = models.CharField(max_length=255, help_text="(максимальное число символов: 255)",
                             verbose_name="Название статьи ")

    text = models.TextField(help_text="(максимальное число символов: неограниченно)",
                            verbose_name="Контент статьи ")

    img = models.ImageField(upload_to='media/photos', blank=True,
                            help_text="(соотношение 1:1 или вертикальный прямоугольник, ВАЖНО: первая картинка будет видна на карте товара, остальные только на странице товара)",
                            verbose_name="Загрузка картинки")
    pub_date = models.DateTimeField(verbose_name="Дата", auto_now_add=True, blank=True)

    def __str__(self):
        return f"Название: {self.title} Дата публикации: {self.pub_date}"

    class Meta:
        verbose_name = "Статья"
        verbose_name_plural = "Статьи"


class SiteProfile(models.Model):
    page_name = models.CharField(max_length=255, help_text="(максимальное число символов: 255)",
                                 verbose_name="Название страницы ")

    page_icon = models.ImageField(upload_to='media/site',
                                  help_text="(видна на закладках)",
                                  verbose_name="Иконка страницы ")

    page_desc = models.TextField(help_text="(необязательно, нужен только для сео)",
                                 default="Крутой магазин корейской продукции",

templates/shop/about.html
{% extends 'shop/base.html' %}
{% load static %}
{% block content %}

    <div class="sub-banner">
        <div style="background-image: url('{% static 'Shop/img/back.jpg' %}')" class="page-info">
        </div>
    </div>

    <main class="about-main">
        <section class="">
            <div class="container">
                <div class="row mt-5">
                    <h1 style="margin: 0 auto; font-weight: 500; font-size: 3em">О магазине</h1>
                </div>

                {% for i in items %}

                    {{ i|safe }}

                {% endfor %}

                {% if articles.count > 0 %}
                    <div class="row mt-5">
                        <h2 style="margin: 0 auto; font-weight: 500; font-size: 3em"> Новости и акции </h2>
                    </div>

                    {% for a in articles %}
                        <div id="news{{ a.id }}"
                             class="row no-gutters border rounded overflow-hidden flex-md-row mb-4 shadow-sm h-md-250 position-relative mt-5">
                            <div class="col-lg-4 col-md-4 col-12">
                                <img src="{{ a.img.url }}" alt="" class="img-fluid">
                            </div>
                            <div class="col-lg-8 col-md-8 col-12 p-4 d-flex flex-column position-static">
                                <h3 class="mb-0">{{ a.title }}</h3>
                                <div class="mb-1 text-muted">{{ a.pub_date }}</div>
                                <p class="card-text mb-auto" style="word-break: break-all">{{ a.text }}</p>
                            </div>
                        </div>
                    {% endfor %}
                {% endif %}
            </div>
        </section>
    </main>


{% endblock content %}

templates/shop/base.html
{% load static %}
{% load temp_filter %}

<!DOCTYPE html>
<html lang="ru">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{{ pagename }}</title>
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="keywords" content="">
    <meta name="description" content="{{ site.description }}">
    <meta name="author" content="">

    <link rel="shortcut icon" href="{{ site.page_icon.url }}" type="image/x-icon">
    <link rel="apple-touch-icon" href="{% static '/Shop/images/apple-touch-icon.png' %}">


    <link rel="stylesheet" href="{% static 'Shop/bootstrap-4.5.2-dist/css/bootstrap.css' %}">
    <link rel="stylesheet" href="{% static 'Shop/fontawesome-free-5.15.1-web/css/all.css' %}">
    <link rel="stylesheet" href="{% static 'Shop/simple-text-rotator-master/simpletextrotator.css' %}">
    <link rel="stylesheet" href="{% static 'Shop/dist/assets/owl.carousel.css' %}">
    <link rel="stylesheet" href="{% static 'Shop/dist/assets/owl.theme.default.css' %}">
    <link rel="stylesheet" href="{% static 'Shop/dist/assets/owl.theme.green.css' %}">
    <link rel="stylesheet" href="{% static 'Shop/css/style.css' %}">
    <link rel="stylesheet" href="{% static 'Shop/css/sidebar.css' %}">
    <link rel="stylesheet" href="{% static 'Shop/css/mobile_navbar.css' %}">
    <link rel="stylesheet" href="{% static 'Shop/css/fotorama.css' %}">
    <link rel="stylesheet" href="{% static 'Shop/css/ranger.css' %}">
    <link rel="stylesheet" href="{% static 'Shop/css/rating.css' %}">
    <link rel="stylesheet" href="{% static 'Shop/css/selector.css' %}">
    <link href="https://cdn.jsdelivr.net/gh/StephanWagner/jBox@v1.2.0/dist/jBox.all.min.css" rel="stylesheet">

</head>
<body>
{% if articles.count > 0 %}
    <div class="scroll-left">
        <p style="-moz-animation: scroll-left {{ articles.count|multiplication }}s linear infinite;
                -webkit-animation: scroll-left {{ articles.count|multiplication }}s linear infinite;
                animation: scroll-left {{ articles.count|multiplication }}s linear infinite;">
            <a></a>
            {% for a in articles %}
                <a href="{% url 'shop:about' %}#news{{ a.id }}">{{ a.title }}</a>
            {% endfor %}
        </p>
    </div>
{% endif %}
<header id="main_header" class="main-header {{ type }}">
    <nav class="navbar navbar-expand-lg main-navigation">
        <div class="navbar-brand brand-box">
            <a href="{% url 'shop:index' %}"><img src="{{ site.main_logo.url }}" alt="Логотип магазина"
                                                  class="img-fluid"></a>
        </div>
        <div class="nav-box">
            <ul class="navbar-nav ml-auto">
                <li class="nav-item active ml-auto">
                    <a class="nav-link" href="{% url 'shop:index' %}">Главная</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'shop:about' %}">О магазине</a>
                </li>
                <li class="nav-item dropdown">
                    <a class="nav-link dropdown-toggle" id="navbarDropdown" role="button"
                       data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                        Товары
                    </a>
                    <div class="dropdown-menu header-menu" aria-labelledby="navbarDropdown">
                        <div class="head-menu-wrap">
                            <div class="cat-row">
                                {% for cat in categs %}
                                    <div class="menu-cat">
                                        <a class="" href="{% url 'shop:product' cat.id %}">{{ cat.name }}</a>
                                        <div class="dropdown-divider"></div>
                                        <ul class="sub-cats">
                                            {% for s in cat.subcategory_set.all %}
                                                <li>
                                                    <a href="{% url 'shop:product' cat.id %}?subcat={{ s.id }}">{{ s.name }}</a>
                                                </li>
                                            {% endfor %}
                                        </ul>
                                    </div>
                                {% endfor %}
                            </div>
                        </div>
                    </div>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="#contacts">Контакты</a>
                </li>
                <li class="nav-item cart-box">
                    <a class="nav-link" href="{% url 'shop:cart' %}"><i class="fas fa-shopping-cart"></i>
                        <span id="cartProductAmount"><sup>{{ cartSize }}</sup></span></a>
                </li>
            </ul>
        </div>
        <button type="button" class="active" id="sidebarCollapse" class="navbar-btn">
            <span></span>
            <span></span>
            <span></span>
        </button>
    </nav>
    <nav id="sidebar" class="active">
        <ul class="list-unstyled components">
            <li class="active">
                <a href="{% url 'shop:index' %}"> Главная </a>
            </li>

            <li class="active">
                <a href="{% url 'shop:about' %}"> О магазине </a>
            </li>

            <li>
                <a href="#pageSubmenu" data-toggle="collapse" aria-expanded="false"
                   class="dropdown-toggle dropd collapsed">Товары</a>
                <ul class="collapse list-unstyled" id="pageSubmenu">
                    {% for cat in categs %}
                        <li>
                            <a href="{% url 'shop:product' pk=cat.id %}">{{ cat.name }}</a>
                        </li>
                    {% endfor %}
                </ul>
            </li>
            <li>
                <a href="#contacts">Контакты</a>
            </li>

            <li>
                <a href="{% url 'shop:cart' %}">Корзина</a>
            </li>
        </ul>
    </nav>
</header>

{% block content %}
{% endblock content %}

<footer class="main-footer">
    <div class="container">
        <div class="row d-flex align-content-start flex-lg-wrap flex-wrap-reverse">
            <div class="col-lg-4 col-md-10 col-sm-10 ml-auto mr-auto" id="contacts">
                <h3 class="mt-5">Контакты</h3>
                <p>
                    Телефон: <br><span class="phone"> {{ site.phone_number }} </span>
                    <br>
                    <br>
                    Адрес: <br><span class="address">{{ site.address }}</span>
                    <br>
                    <br>
                    Социальные сети:

                </p>
                <ul class="socials">
                    <li><a href="{{ site.instagram }}"> <img src="{% static 'Shop/img/instagram.png' %}"
                                                             alt="инстаграм"></a></li>
                    <li><a href="{{ site.whatsup }}"> <img src="{% static 'Shop/img/whatsapp.png' %}" alt="ватсап"></a>
                    </li>
                    <li><a href="{{ site.email }}"> <img src="{% static 'Shop/img/gmail.png' %}" alt="почта"></a></li>
                </ul>
            </div>
            <div class="col-lg-4 col-md-10 col-sm-10 ml-auto mr-auto">
                <h3 class="mt-5">Обратная связь</h3>

                <form name="call_back_form" action="{% url 'shop:callback' %}" method="post" id="callback-form"
                      class="callback-form">
                    {% csrf_token %}
                    <input type="text" name="callname" id="callname" placeholder="Ваше имя" required>
                    <input type="text" name="callphone" id="callphone" placeholder="Ваш номер телефона" required>
                    <button type="submit" class="callback-btn"> Отправить</button>
                </form>

                <div class="d-flex flex-column text-center w-100 mt-5">

                    <a href="{% url 'shop:oferta' %}" class="d-block"> Публичная оферта </a>
                    <a href="{% url 'shop:privacy' %}" class="d-block"> Политика конфиденциальности </a>

                </div>
            </div>
            <div class="col-lg-4 col-md-10 col-sm-10 ml-auto mr-auto">
                <h3 class="mt-5">Часто задаваемые вопросы</h3>

                <div class="questions-box">
                    {% for q in questions %}
                        <div class="question">
                            <p>
                                <a class="" data-toggle="collapse" href="#question1" role="button" aria-expanded="false"
                                   aria-controls="question{{ q.id }}">
                                    {{ q.question }}
                                </a>
                            </p>
                            <div class="collapse" id="question{{ q.id }}">
                                <div class="card card-body">
                                    <p> {{ q.answer }}</p>
                                </div>
                            </div>
                        </div>
                    {% endfor %}
                </div>
            </div>
        </div>
    </div>
</footer>


<script src="{% static 'Shop/js/jquery-3.2.1.min.js' %}" type="text/javascript"></script>
<script type="text/javascript"
        src="{% static 'Shop/simple-text-rotator-master/jquery.simple-text-rotator.js' %}"></script>
<script src="{% static 'Shop/bootstrap-4.5.2-dist/js/bootstrap.js' %}"></script>
<script src="{% static 'Shop/dist/owl.carousel.js' %}"></script>
<script src="{% static 'Shop/js/fotorama.js' %}"></script>
<script type="text/javascript" src="{% static 'Shop/js/main.js' %}"></script>
<script src="{% static 'Shop/js/sidebar.js' %}"></script>
<script src="{% static 'Shop/js/ranger.js' %}"></script>
<script src="{% static 'Shop/js/prod-details.js' %}"></script>
<script src="{% static 'Shop/js/makeorder.js' %}"></script>
<script src="{% static 'Shop/js/rating.js' %}"></script>
<script src="{% static 'Shop/js/selector.js' %}"></script>

<script src="https://cdn.jsdelivr.net/gh/StephanWagner/jBox@v1.2.0/dist/jBox.all.min.js"></script>


</body>
</html>

templates/shop/index.html
{% extends 'shop/base.html' %}
{% load static %}
{% block content %}

    <div class="banner-wrapper">
        <div class="main-banner">
            <img src="media/{{ site.home_banner }}" alt="{{ site.home_banner_alt }}">
        </div>

        <div class="slogan">
            <h1> Наш магазин </h1>
            <p><span class="rotate">{{ site.slogan }}</span></p>
        </div>
    </div>

    <main class="main-content p-0">
        <section class="category-screen">
            <h2> Категории </h2>
            <ul class="category-list">
                {% for cat in categs %}
                    <li class="cat"><a href="{% url 'shop:product' pk=cat.id %}">{{ cat.name }}</a>
                        <img align="middle" src="{{ cat.banner.url }}" alt="{{ cat.banner_alt }}" class="bg">
                    </li>
                {% endfor %}
            </ul>
        </section>
        <section class="recomendation-screen">
            <h2> Mы рекомендуем </h2>
            <div class="wrap-rec-banner position-relative">
                <div class="content-wrapper">
                    <div class="container">
                        <div class="row d-flex justify-content-between">
                            <div class="col-lg-12 col-md-12 col-sm-9 col-8 m-auto position-relative">
                                <div class="owl-carousel">
                                    {% for prod in prod_recom %}
                                        <div class="product-box">
                                            <div class="card">
                                                <div class="tag-box">
                                                    <span>{{ prod.tag.name }}</span>
                                                </div>
                                                <div class="prod-wrap">
                                                    <div class="img-box">
                                                        <img src="{{ prod.productphoto_set.all.0.img.url }}"
                                                             alt="{{ prod.productphoto_set.all.0.alt }}">
                                                    </div>
                                                    <div class="content-box">
                                                        <h3>{{ prod.name }}</h3>
                                                        <p>{{ prod.desc_short }}</p>
                                                        <a href="{% url 'shop:product_detail' prod.id %}">Подробнее</a>
                                                    </div>
                                                </div>
                                            </div>
                                        </div>
                                    {% endfor %}
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="main-banner">
                    <img src="{% static 'Shop/img/recomend-banner.png' %}" alt="Фон рекомендаций">
                </div>
            </div>
        </section>
    </main>

{% endblock content %}